# Generated by Django 4.0.6 on 2022-08-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='name',
        ),
    ]
