# Generated by Django 4.0.6 on 2022-07-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('section', models.CharField(choices=[('Home', 'Home'), ('Ofice', 'Office')], max_length=20)),
                ('picture', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
